### ISSUE TITLE
Still issues with light theme

### ISSUE THREAD

**Issue by Tdue21** [RPTools/rptools-doc#8]
Uh, there is still an issue with the light theme, examples are completely unreadable: 

![image](https://user-images.githubusercontent.com/2953375/185555814-e6785100-60c0-4aaf-adac-3a57cc996cdd.png)

Sorry...

**Comment by cwisniew** [comment]
If I get really close to my screen I can read it! So must be your screen / distance! :)
I will have a look at it tonight

**Comment by Tdue21** [comment]
> If I get really close to my screen I can read it! So must be your screen / distance! :) I will have a look at it tonight

Hah! Yeah, must be it ;)
